// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler_test

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/zulerne/go-mentor-junior/order/internal/domain"
)

// NewMockCustomer creates a new instance of MockCustomer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockCustomer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockCustomer is an autogenerated mock type for the Customer type
type MockCustomer struct {
	mock.Mock
}

type MockCustomer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomer) EXPECT() *MockCustomer_Expecter {
	return &MockCustomer_Expecter{mock: &_m.Mock}
}

// AddItemToCart provides a mock function for the type MockCustomer
func (_mock *MockCustomer) AddItemToCart(ctx context.Context, customerID uuid.UUID, restaurantID uuid.UUID, menuItemID uuid.UUID, quantity int32, instructions string) (domain.Cart, error) {
	ret := _mock.Called(ctx, customerID, restaurantID, menuItemID, quantity, instructions)

	if len(ret) == 0 {
		panic("no return value specified for AddItemToCart")
	}

	var r0 domain.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, int32, string) (domain.Cart, error)); ok {
		return returnFunc(ctx, customerID, restaurantID, menuItemID, quantity, instructions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, int32, string) domain.Cart); ok {
		r0 = returnFunc(ctx, customerID, restaurantID, menuItemID, quantity, instructions)
	} else {
		r0 = ret.Get(0).(domain.Cart)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, int32, string) error); ok {
		r1 = returnFunc(ctx, customerID, restaurantID, menuItemID, quantity, instructions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomer_AddItemToCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddItemToCart'
type MockCustomer_AddItemToCart_Call struct {
	*mock.Call
}

// AddItemToCart is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID uuid.UUID
//   - restaurantID uuid.UUID
//   - menuItemID uuid.UUID
//   - quantity int32
//   - instructions string
func (_e *MockCustomer_Expecter) AddItemToCart(ctx any, customerID any, restaurantID any, menuItemID any, quantity any, instructions any) *MockCustomer_AddItemToCart_Call {
	return &MockCustomer_AddItemToCart_Call{Call: _e.mock.On("AddItemToCart", ctx, customerID, restaurantID, menuItemID, quantity, instructions)}
}

func (_c *MockCustomer_AddItemToCart_Call) Run(run func(ctx context.Context, customerID uuid.UUID, restaurantID uuid.UUID, menuItemID uuid.UUID, quantity int32, instructions string)) *MockCustomer_AddItemToCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 int32
		if args[4] != nil {
			arg4 = args[4].(int32)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockCustomer_AddItemToCart_Call) Return(cart domain.Cart, err error) *MockCustomer_AddItemToCart_Call {
	_c.Call.Return(cart, err)
	return _c
}

func (_c *MockCustomer_AddItemToCart_Call) RunAndReturn(run func(ctx context.Context, customerID uuid.UUID, restaurantID uuid.UUID, menuItemID uuid.UUID, quantity int32, instructions string) (domain.Cart, error)) *MockCustomer_AddItemToCart_Call {
	_c.Call.Return(run)
	return _c
}

// CancelOrder provides a mock function for the type MockCustomer
func (_mock *MockCustomer) CancelOrder(ctx context.Context, customerID uuid.UUID, orderID uuid.UUID) (domain.Order, error) {
	ret := _mock.Called(ctx, customerID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (domain.Order, error)); ok {
		return returnFunc(ctx, customerID, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) domain.Order); ok {
		r0 = returnFunc(ctx, customerID, orderID)
	} else {
		r0 = ret.Get(0).(domain.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, customerID, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomer_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type MockCustomer_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID uuid.UUID
//   - orderID uuid.UUID
func (_e *MockCustomer_Expecter) CancelOrder(ctx any, customerID any, orderID any) *MockCustomer_CancelOrder_Call {
	return &MockCustomer_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, customerID, orderID)}
}

func (_c *MockCustomer_CancelOrder_Call) Run(run func(ctx context.Context, customerID uuid.UUID, orderID uuid.UUID)) *MockCustomer_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCustomer_CancelOrder_Call) Return(order domain.Order, err error) *MockCustomer_CancelOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockCustomer_CancelOrder_Call) RunAndReturn(run func(ctx context.Context, customerID uuid.UUID, orderID uuid.UUID) (domain.Order, error)) *MockCustomer_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function for the type MockCustomer
func (_mock *MockCustomer) CreateOrder(ctx context.Context, customerID uuid.UUID, deliveryAddress string) (domain.Order, error) {
	ret := _mock.Called(ctx, customerID, deliveryAddress)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (domain.Order, error)); ok {
		return returnFunc(ctx, customerID, deliveryAddress)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) domain.Order); ok {
		r0 = returnFunc(ctx, customerID, deliveryAddress)
	} else {
		r0 = ret.Get(0).(domain.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, customerID, deliveryAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomer_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockCustomer_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID uuid.UUID
//   - deliveryAddress string
func (_e *MockCustomer_Expecter) CreateOrder(ctx any, customerID any, deliveryAddress any) *MockCustomer_CreateOrder_Call {
	return &MockCustomer_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, customerID, deliveryAddress)}
}

func (_c *MockCustomer_CreateOrder_Call) Run(run func(ctx context.Context, customerID uuid.UUID, deliveryAddress string)) *MockCustomer_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCustomer_CreateOrder_Call) Return(order domain.Order, err error) *MockCustomer_CreateOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockCustomer_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, customerID uuid.UUID, deliveryAddress string) (domain.Order, error)) *MockCustomer_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllOrders provides a mock function for the type MockCustomer
func (_mock *MockCustomer) GetAllOrders(ctx context.Context, customerID uuid.UUID) ([]domain.Order, error) {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllOrders")
	}

	var r0 []domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.Order, error)); ok {
		return returnFunc(ctx, customerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.Order); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomer_GetAllOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllOrders'
type MockCustomer_GetAllOrders_Call struct {
	*mock.Call
}

// GetAllOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID uuid.UUID
func (_e *MockCustomer_Expecter) GetAllOrders(ctx any, customerID any) *MockCustomer_GetAllOrders_Call {
	return &MockCustomer_GetAllOrders_Call{Call: _e.mock.On("GetAllOrders", ctx, customerID)}
}

func (_c *MockCustomer_GetAllOrders_Call) Run(run func(ctx context.Context, customerID uuid.UUID)) *MockCustomer_GetAllOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomer_GetAllOrders_Call) Return(orders []domain.Order, err error) *MockCustomer_GetAllOrders_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockCustomer_GetAllOrders_Call) RunAndReturn(run func(ctx context.Context, customerID uuid.UUID) ([]domain.Order, error)) *MockCustomer_GetAllOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetCart provides a mock function for the type MockCustomer
func (_mock *MockCustomer) GetCart(ctx context.Context, customerID uuid.UUID) (domain.Cart, error) {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for GetCart")
	}

	var r0 domain.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Cart, error)); ok {
		return returnFunc(ctx, customerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Cart); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		r0 = ret.Get(0).(domain.Cart)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomer_GetCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCart'
type MockCustomer_GetCart_Call struct {
	*mock.Call
}

// GetCart is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID uuid.UUID
func (_e *MockCustomer_Expecter) GetCart(ctx any, customerID any) *MockCustomer_GetCart_Call {
	return &MockCustomer_GetCart_Call{Call: _e.mock.On("GetCart", ctx, customerID)}
}

func (_c *MockCustomer_GetCart_Call) Run(run func(ctx context.Context, customerID uuid.UUID)) *MockCustomer_GetCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomer_GetCart_Call) Return(cart domain.Cart, err error) *MockCustomer_GetCart_Call {
	_c.Call.Return(cart, err)
	return _c
}

func (_c *MockCustomer_GetCart_Call) RunAndReturn(run func(ctx context.Context, customerID uuid.UUID) (domain.Cart, error)) *MockCustomer_GetCart_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function for the type MockCustomer
func (_mock *MockCustomer) GetOrder(ctx context.Context, customerID uuid.UUID, orderID uuid.UUID) (domain.Order, error) {
	ret := _mock.Called(ctx, customerID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (domain.Order, error)); ok {
		return returnFunc(ctx, customerID, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) domain.Order); ok {
		r0 = returnFunc(ctx, customerID, orderID)
	} else {
		r0 = ret.Get(0).(domain.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, customerID, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomer_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockCustomer_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID uuid.UUID
//   - orderID uuid.UUID
func (_e *MockCustomer_Expecter) GetOrder(ctx any, customerID any, orderID any) *MockCustomer_GetOrder_Call {
	return &MockCustomer_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, customerID, orderID)}
}

func (_c *MockCustomer_GetOrder_Call) Run(run func(ctx context.Context, customerID uuid.UUID, orderID uuid.UUID)) *MockCustomer_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCustomer_GetOrder_Call) Return(order domain.Order, err error) *MockCustomer_GetOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockCustomer_GetOrder_Call) RunAndReturn(run func(ctx context.Context, customerID uuid.UUID, orderID uuid.UUID) (domain.Order, error)) *MockCustomer_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveItemFromCart provides a mock function for the type MockCustomer
func (_mock *MockCustomer) RemoveItemFromCart(ctx context.Context, customerID uuid.UUID, menuItemID uuid.UUID) error {
	ret := _mock.Called(ctx, customerID, menuItemID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveItemFromCart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, customerID, menuItemID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomer_RemoveItemFromCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveItemFromCart'
type MockCustomer_RemoveItemFromCart_Call struct {
	*mock.Call
}

// RemoveItemFromCart is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID uuid.UUID
//   - menuItemID uuid.UUID
func (_e *MockCustomer_Expecter) RemoveItemFromCart(ctx any, customerID any, menuItemID any) *MockCustomer_RemoveItemFromCart_Call {
	return &MockCustomer_RemoveItemFromCart_Call{Call: _e.mock.On("RemoveItemFromCart", ctx, customerID, menuItemID)}
}

func (_c *MockCustomer_RemoveItemFromCart_Call) Run(run func(ctx context.Context, customerID uuid.UUID, menuItemID uuid.UUID)) *MockCustomer_RemoveItemFromCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCustomer_RemoveItemFromCart_Call) Return(err error) *MockCustomer_RemoveItemFromCart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomer_RemoveItemFromCart_Call) RunAndReturn(run func(ctx context.Context, customerID uuid.UUID, menuItemID uuid.UUID) error) *MockCustomer_RemoveItemFromCart_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRestaurant creates a new instance of MockRestaurant. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRestaurant(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRestaurant {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRestaurant{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRestaurant is an autogenerated mock type for the Restaurant type
type MockRestaurant struct {
	mock.Mock
}

type MockRestaurant_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRestaurant) EXPECT() *MockRestaurant_Expecter {
	return &MockRestaurant_Expecter{mock: &_m.Mock}
}

// AcceptOrder provides a mock function for the type MockRestaurant
func (_mock *MockRestaurant) AcceptOrder(ctx context.Context, restaurantID uuid.UUID, orderID uuid.UUID) (domain.Order, error) {
	ret := _mock.Called(ctx, restaurantID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for AcceptOrder")
	}

	var r0 domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (domain.Order, error)); ok {
		return returnFunc(ctx, restaurantID, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) domain.Order); ok {
		r0 = returnFunc(ctx, restaurantID, orderID)
	} else {
		r0 = ret.Get(0).(domain.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, restaurantID, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestaurant_AcceptOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptOrder'
type MockRestaurant_AcceptOrder_Call struct {
	*mock.Call
}

// AcceptOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID uuid.UUID
//   - orderID uuid.UUID
func (_e *MockRestaurant_Expecter) AcceptOrder(ctx any, restaurantID any, orderID any) *MockRestaurant_AcceptOrder_Call {
	return &MockRestaurant_AcceptOrder_Call{Call: _e.mock.On("AcceptOrder", ctx, restaurantID, orderID)}
}

func (_c *MockRestaurant_AcceptOrder_Call) Run(run func(ctx context.Context, restaurantID uuid.UUID, orderID uuid.UUID)) *MockRestaurant_AcceptOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRestaurant_AcceptOrder_Call) Return(order domain.Order, err error) *MockRestaurant_AcceptOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockRestaurant_AcceptOrder_Call) RunAndReturn(run func(ctx context.Context, restaurantID uuid.UUID, orderID uuid.UUID) (domain.Order, error)) *MockRestaurant_AcceptOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrders provides a mock function for the type MockRestaurant
func (_mock *MockRestaurant) GetOrders(ctx context.Context, restaurantID uuid.UUID) ([]domain.Order, error) {
	ret := _mock.Called(ctx, restaurantID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrders")
	}

	var r0 []domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.Order, error)); ok {
		return returnFunc(ctx, restaurantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.Order); ok {
		r0 = returnFunc(ctx, restaurantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, restaurantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestaurant_GetOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrders'
type MockRestaurant_GetOrders_Call struct {
	*mock.Call
}

// GetOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID uuid.UUID
func (_e *MockRestaurant_Expecter) GetOrders(ctx any, restaurantID any) *MockRestaurant_GetOrders_Call {
	return &MockRestaurant_GetOrders_Call{Call: _e.mock.On("GetOrders", ctx, restaurantID)}
}

func (_c *MockRestaurant_GetOrders_Call) Run(run func(ctx context.Context, restaurantID uuid.UUID)) *MockRestaurant_GetOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRestaurant_GetOrders_Call) Return(orders []domain.Order, err error) *MockRestaurant_GetOrders_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockRestaurant_GetOrders_Call) RunAndReturn(run func(ctx context.Context, restaurantID uuid.UUID) ([]domain.Order, error)) *MockRestaurant_GetOrders_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareOrder provides a mock function for the type MockRestaurant
func (_mock *MockRestaurant) PrepareOrder(ctx context.Context, restaurantID uuid.UUID, orderID uuid.UUID) (domain.Order, error) {
	ret := _mock.Called(ctx, restaurantID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for PrepareOrder")
	}

	var r0 domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (domain.Order, error)); ok {
		return returnFunc(ctx, restaurantID, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) domain.Order); ok {
		r0 = returnFunc(ctx, restaurantID, orderID)
	} else {
		r0 = ret.Get(0).(domain.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, restaurantID, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestaurant_PrepareOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareOrder'
type MockRestaurant_PrepareOrder_Call struct {
	*mock.Call
}

// PrepareOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID uuid.UUID
//   - orderID uuid.UUID
func (_e *MockRestaurant_Expecter) PrepareOrder(ctx any, restaurantID any, orderID any) *MockRestaurant_PrepareOrder_Call {
	return &MockRestaurant_PrepareOrder_Call{Call: _e.mock.On("PrepareOrder", ctx, restaurantID, orderID)}
}

func (_c *MockRestaurant_PrepareOrder_Call) Run(run func(ctx context.Context, restaurantID uuid.UUID, orderID uuid.UUID)) *MockRestaurant_PrepareOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRestaurant_PrepareOrder_Call) Return(order domain.Order, err error) *MockRestaurant_PrepareOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockRestaurant_PrepareOrder_Call) RunAndReturn(run func(ctx context.Context, restaurantID uuid.UUID, orderID uuid.UUID) (domain.Order, error)) *MockRestaurant_PrepareOrder_Call {
	_c.Call.Return(run)
	return _c
}

// ReadyOrder provides a mock function for the type MockRestaurant
func (_mock *MockRestaurant) ReadyOrder(ctx context.Context, restaurantID uuid.UUID, orderID uuid.UUID) (domain.Order, error) {
	ret := _mock.Called(ctx, restaurantID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for ReadyOrder")
	}

	var r0 domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (domain.Order, error)); ok {
		return returnFunc(ctx, restaurantID, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) domain.Order); ok {
		r0 = returnFunc(ctx, restaurantID, orderID)
	} else {
		r0 = ret.Get(0).(domain.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, restaurantID, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestaurant_ReadyOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadyOrder'
type MockRestaurant_ReadyOrder_Call struct {
	*mock.Call
}

// ReadyOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID uuid.UUID
//   - orderID uuid.UUID
func (_e *MockRestaurant_Expecter) ReadyOrder(ctx any, restaurantID any, orderID any) *MockRestaurant_ReadyOrder_Call {
	return &MockRestaurant_ReadyOrder_Call{Call: _e.mock.On("ReadyOrder", ctx, restaurantID, orderID)}
}

func (_c *MockRestaurant_ReadyOrder_Call) Run(run func(ctx context.Context, restaurantID uuid.UUID, orderID uuid.UUID)) *MockRestaurant_ReadyOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRestaurant_ReadyOrder_Call) Return(order domain.Order, err error) *MockRestaurant_ReadyOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockRestaurant_ReadyOrder_Call) RunAndReturn(run func(ctx context.Context, restaurantID uuid.UUID, orderID uuid.UUID) (domain.Order, error)) *MockRestaurant_ReadyOrder_Call {
	_c.Call.Return(run)
	return _c
}

// RejectOrder provides a mock function for the type MockRestaurant
func (_mock *MockRestaurant) RejectOrder(ctx context.Context, restaurantID uuid.UUID, orderID uuid.UUID, reason string) (domain.Order, error) {
	ret := _mock.Called(ctx, restaurantID, orderID, reason)

	if len(ret) == 0 {
		panic("no return value specified for RejectOrder")
	}

	var r0 domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (domain.Order, error)); ok {
		return returnFunc(ctx, restaurantID, orderID, reason)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) domain.Order); ok {
		r0 = returnFunc(ctx, restaurantID, orderID, reason)
	} else {
		r0 = ret.Get(0).(domain.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, restaurantID, orderID, reason)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestaurant_RejectOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectOrder'
type MockRestaurant_RejectOrder_Call struct {
	*mock.Call
}

// RejectOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID uuid.UUID
//   - orderID uuid.UUID
//   - reason string
func (_e *MockRestaurant_Expecter) RejectOrder(ctx any, restaurantID any, orderID any, reason any) *MockRestaurant_RejectOrder_Call {
	return &MockRestaurant_RejectOrder_Call{Call: _e.mock.On("RejectOrder", ctx, restaurantID, orderID, reason)}
}

func (_c *MockRestaurant_RejectOrder_Call) Run(run func(ctx context.Context, restaurantID uuid.UUID, orderID uuid.UUID, reason string)) *MockRestaurant_RejectOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRestaurant_RejectOrder_Call) Return(order domain.Order, err error) *MockRestaurant_RejectOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockRestaurant_RejectOrder_Call) RunAndReturn(run func(ctx context.Context, restaurantID uuid.UUID, orderID uuid.UUID, reason string) (domain.Order, error)) *MockRestaurant_RejectOrder_Call {
	_c.Call.Return(run)
	return _c
}
