// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package restaurant_test

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/zulerne/go-mentor-junior/order/internal/domain"
)

// NewMockOrderStore creates a new instance of MockOrderStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockOrderStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockOrderStore is an autogenerated mock type for the OrderStore type
type MockOrderStore struct {
	mock.Mock
}

type MockOrderStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderStore) EXPECT() *MockOrderStore_Expecter {
	return &MockOrderStore_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockOrderStore
func (_mock *MockOrderStore) Find(ctx context.Context, id uuid.UUID) (domain.Order, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Order, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderStore_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockOrderStore_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockOrderStore_Expecter) Find(ctx any, id any) *MockOrderStore_Find_Call {
	return &MockOrderStore_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockOrderStore_Find_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockOrderStore_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderStore_Find_Call) Return(order domain.Order, err error) *MockOrderStore_Find_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderStore_Find_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Order, error)) *MockOrderStore_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByRestaurant provides a mock function for the type MockOrderStore
func (_mock *MockOrderStore) FindByRestaurant(ctx context.Context, restaurantID uuid.UUID) ([]domain.Order, error) {
	ret := _mock.Called(ctx, restaurantID)

	if len(ret) == 0 {
		panic("no return value specified for FindByRestaurant")
	}

	var r0 []domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.Order, error)); ok {
		return returnFunc(ctx, restaurantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.Order); ok {
		r0 = returnFunc(ctx, restaurantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, restaurantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderStore_FindByRestaurant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByRestaurant'
type MockOrderStore_FindByRestaurant_Call struct {
	*mock.Call
}

// FindByRestaurant is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID uuid.UUID
func (_e *MockOrderStore_Expecter) FindByRestaurant(ctx any, restaurantID any) *MockOrderStore_FindByRestaurant_Call {
	return &MockOrderStore_FindByRestaurant_Call{Call: _e.mock.On("FindByRestaurant", ctx, restaurantID)}
}

func (_c *MockOrderStore_FindByRestaurant_Call) Run(run func(ctx context.Context, restaurantID uuid.UUID)) *MockOrderStore_FindByRestaurant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderStore_FindByRestaurant_Call) Return(orders []domain.Order, err error) *MockOrderStore_FindByRestaurant_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrderStore_FindByRestaurant_Call) RunAndReturn(run func(ctx context.Context, restaurantID uuid.UUID) ([]domain.Order, error)) *MockOrderStore_FindByRestaurant_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockOrderStore
func (_mock *MockOrderStore) Update(ctx context.Context, order domain.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOrderStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - order domain.Order
func (_e *MockOrderStore_Expecter) Update(ctx any, order any) *MockOrderStore_Update_Call {
	return &MockOrderStore_Update_Call{Call: _e.mock.On("Update", ctx, order)}
}

func (_c *MockOrderStore_Update_Call) Run(run func(ctx context.Context, order domain.Order)) *MockOrderStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Order
		if args[1] != nil {
			arg1 = args[1].(domain.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderStore_Update_Call) Return(err error) *MockOrderStore_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderStore_Update_Call) RunAndReturn(run func(ctx context.Context, order domain.Order) error) *MockOrderStore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeliveryProvider creates a new instance of MockDeliveryProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeliveryProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeliveryProvider {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockDeliveryProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockDeliveryProvider is an autogenerated mock type for the DeliveryProvider type
type MockDeliveryProvider struct {
	mock.Mock
}

type MockDeliveryProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeliveryProvider) EXPECT() *MockDeliveryProvider_Expecter {
	return &MockDeliveryProvider_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockDeliveryProvider
func (_mock *MockDeliveryProvider) Create(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeliveryProvider_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDeliveryProvider_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockDeliveryProvider_Expecter) Create(ctx any, orderID any) *MockDeliveryProvider_Create_Call {
	return &MockDeliveryProvider_Create_Call{Call: _e.mock.On("Create", ctx, orderID)}
}

func (_c *MockDeliveryProvider_Create_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockDeliveryProvider_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeliveryProvider_Create_Call) Return(err error) *MockDeliveryProvider_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeliveryProvider_Create_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockDeliveryProvider_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockDeliveryProvider
func (_mock *MockDeliveryProvider) Start(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeliveryProvider_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockDeliveryProvider_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockDeliveryProvider_Expecter) Start(ctx any, orderID any) *MockDeliveryProvider_Start_Call {
	return &MockDeliveryProvider_Start_Call{Call: _e.mock.On("Start", ctx, orderID)}
}

func (_c *MockDeliveryProvider_Start_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockDeliveryProvider_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeliveryProvider_Start_Call) Return(err error) *MockDeliveryProvider_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeliveryProvider_Start_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockDeliveryProvider_Start_Call {
	_c.Call.Return(run)
	return _c
}
