// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package customer_test

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/zulerne/go-mentor-junior/order/internal/domain"
)

// NewMockOrderStore creates a new instance of MockOrderStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockOrderStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockOrderStore is an autogenerated mock type for the OrderStore type
type MockOrderStore struct {
	mock.Mock
}

type MockOrderStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderStore) EXPECT() *MockOrderStore_Expecter {
	return &MockOrderStore_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockOrderStore
func (_mock *MockOrderStore) Find(ctx context.Context, id uuid.UUID) (domain.Order, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Order, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderStore_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockOrderStore_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockOrderStore_Expecter) Find(ctx any, id any) *MockOrderStore_Find_Call {
	return &MockOrderStore_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockOrderStore_Find_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockOrderStore_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderStore_Find_Call) Return(order domain.Order, err error) *MockOrderStore_Find_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderStore_Find_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Order, error)) *MockOrderStore_Find_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllOrders provides a mock function for the type MockOrderStore
func (_mock *MockOrderStore) GetAllOrders(ctx context.Context, customerID uuid.UUID) ([]domain.Order, error) {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllOrders")
	}

	var r0 []domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.Order, error)); ok {
		return returnFunc(ctx, customerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.Order); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderStore_GetAllOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllOrders'
type MockOrderStore_GetAllOrders_Call struct {
	*mock.Call
}

// GetAllOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID uuid.UUID
func (_e *MockOrderStore_Expecter) GetAllOrders(ctx any, customerID any) *MockOrderStore_GetAllOrders_Call {
	return &MockOrderStore_GetAllOrders_Call{Call: _e.mock.On("GetAllOrders", ctx, customerID)}
}

func (_c *MockOrderStore_GetAllOrders_Call) Run(run func(ctx context.Context, customerID uuid.UUID)) *MockOrderStore_GetAllOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderStore_GetAllOrders_Call) Return(orders []domain.Order, err error) *MockOrderStore_GetAllOrders_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrderStore_GetAllOrders_Call) RunAndReturn(run func(ctx context.Context, customerID uuid.UUID) ([]domain.Order, error)) *MockOrderStore_GetAllOrders_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockOrderStore
func (_mock *MockOrderStore) Update(ctx context.Context, order domain.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOrderStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - order domain.Order
func (_e *MockOrderStore_Expecter) Update(ctx any, order any) *MockOrderStore_Update_Call {
	return &MockOrderStore_Update_Call{Call: _e.mock.On("Update", ctx, order)}
}

func (_c *MockOrderStore_Update_Call) Run(run func(ctx context.Context, order domain.Order)) *MockOrderStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Order
		if args[1] != nil {
			arg1 = args[1].(domain.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderStore_Update_Call) Return(err error) *MockOrderStore_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderStore_Update_Call) RunAndReturn(run func(ctx context.Context, order domain.Order) error) *MockOrderStore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCartStore creates a new instance of MockCartStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCartStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCartStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockCartStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockCartStore is an autogenerated mock type for the CartStore type
type MockCartStore struct {
	mock.Mock
}

type MockCartStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCartStore) EXPECT() *MockCartStore_Expecter {
	return &MockCartStore_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockCartStore
func (_mock *MockCartStore) Find(ctx context.Context, customerID uuid.UUID) (domain.Cart, error) {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 domain.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Cart, error)); ok {
		return returnFunc(ctx, customerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Cart); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		r0 = ret.Get(0).(domain.Cart)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCartStore_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockCartStore_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID uuid.UUID
func (_e *MockCartStore_Expecter) Find(ctx any, customerID any) *MockCartStore_Find_Call {
	return &MockCartStore_Find_Call{Call: _e.mock.On("Find", ctx, customerID)}
}

func (_c *MockCartStore_Find_Call) Run(run func(ctx context.Context, customerID uuid.UUID)) *MockCartStore_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCartStore_Find_Call) Return(cart domain.Cart, err error) *MockCartStore_Find_Call {
	_c.Call.Return(cart, err)
	return _c
}

func (_c *MockCartStore_Find_Call) RunAndReturn(run func(ctx context.Context, customerID uuid.UUID) (domain.Cart, error)) *MockCartStore_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockCartStore
func (_mock *MockCartStore) Update(ctx context.Context, customerID uuid.UUID, cart domain.Cart) error {
	ret := _mock.Called(ctx, customerID, cart)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.Cart) error); ok {
		r0 = returnFunc(ctx, customerID, cart)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCartStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCartStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID uuid.UUID
//   - cart domain.Cart
func (_e *MockCartStore_Expecter) Update(ctx any, customerID any, cart any) *MockCartStore_Update_Call {
	return &MockCartStore_Update_Call{Call: _e.mock.On("Update", ctx, customerID, cart)}
}

func (_c *MockCartStore_Update_Call) Run(run func(ctx context.Context, customerID uuid.UUID, cart domain.Cart)) *MockCartStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.Cart
		if args[2] != nil {
			arg2 = args[2].(domain.Cart)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCartStore_Update_Call) Return(err error) *MockCartStore_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCartStore_Update_Call) RunAndReturn(run func(ctx context.Context, customerID uuid.UUID, cart domain.Cart) error) *MockCartStore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRestaurantProvider creates a new instance of MockRestaurantProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRestaurantProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRestaurantProvider {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRestaurantProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRestaurantProvider is an autogenerated mock type for the RestaurantProvider type
type MockRestaurantProvider struct {
	mock.Mock
}

type MockRestaurantProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRestaurantProvider) EXPECT() *MockRestaurantProvider_Expecter {
	return &MockRestaurantProvider_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockRestaurantProvider
func (_mock *MockRestaurantProvider) Find(ctx context.Context, restaurantID uuid.UUID) (domain.Restaurant, error) {
	ret := _mock.Called(ctx, restaurantID)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 domain.Restaurant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Restaurant, error)); ok {
		return returnFunc(ctx, restaurantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Restaurant); ok {
		r0 = returnFunc(ctx, restaurantID)
	} else {
		r0 = ret.Get(0).(domain.Restaurant)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, restaurantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestaurantProvider_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockRestaurantProvider_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID uuid.UUID
func (_e *MockRestaurantProvider_Expecter) Find(ctx any, restaurantID any) *MockRestaurantProvider_Find_Call {
	return &MockRestaurantProvider_Find_Call{Call: _e.mock.On("Find", ctx, restaurantID)}
}

func (_c *MockRestaurantProvider_Find_Call) Run(run func(ctx context.Context, restaurantID uuid.UUID)) *MockRestaurantProvider_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRestaurantProvider_Find_Call) Return(restaurant domain.Restaurant, err error) *MockRestaurantProvider_Find_Call {
	_c.Call.Return(restaurant, err)
	return _c
}

func (_c *MockRestaurantProvider_Find_Call) RunAndReturn(run func(ctx context.Context, restaurantID uuid.UUID) (domain.Restaurant, error)) *MockRestaurantProvider_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindItem provides a mock function for the type MockRestaurantProvider
func (_mock *MockRestaurantProvider) FindItem(ctx context.Context, restaurantID uuid.UUID, menuItemID uuid.UUID) (domain.MenuItem, error) {
	ret := _mock.Called(ctx, restaurantID, menuItemID)

	if len(ret) == 0 {
		panic("no return value specified for FindItem")
	}

	var r0 domain.MenuItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (domain.MenuItem, error)); ok {
		return returnFunc(ctx, restaurantID, menuItemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) domain.MenuItem); ok {
		r0 = returnFunc(ctx, restaurantID, menuItemID)
	} else {
		r0 = ret.Get(0).(domain.MenuItem)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, restaurantID, menuItemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestaurantProvider_FindItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindItem'
type MockRestaurantProvider_FindItem_Call struct {
	*mock.Call
}

// FindItem is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID uuid.UUID
//   - menuItemID uuid.UUID
func (_e *MockRestaurantProvider_Expecter) FindItem(ctx any, restaurantID any, menuItemID any) *MockRestaurantProvider_FindItem_Call {
	return &MockRestaurantProvider_FindItem_Call{Call: _e.mock.On("FindItem", ctx, restaurantID, menuItemID)}
}

func (_c *MockRestaurantProvider_FindItem_Call) Run(run func(ctx context.Context, restaurantID uuid.UUID, menuItemID uuid.UUID)) *MockRestaurantProvider_FindItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRestaurantProvider_FindItem_Call) Return(menuItem domain.MenuItem, err error) *MockRestaurantProvider_FindItem_Call {
	_c.Call.Return(menuItem, err)
	return _c
}

func (_c *MockRestaurantProvider_FindItem_Call) RunAndReturn(run func(ctx context.Context, restaurantID uuid.UUID, menuItemID uuid.UUID) (domain.MenuItem, error)) *MockRestaurantProvider_FindItem_Call {
	_c.Call.Return(run)
	return _c
}
